# Makefile to build all the USaBuse AVR projects.

# Call with "make all" to rebuild everything, "make clean" to clean everything,
# "make mostlyclean" to remove all intermediary files but preserve any binaries,

all:

%:
	@echo Executing \"make $@\" on all LUFA library elements.
	@echo
	$(MAKE) -C KeyboardMouseGeneric $@
	@echo
	@echo \"make $@\" operation complete.
